### ISSUE TITLE
Lab02 Q6 + Q7

### ISSUE THREAD

**Issue by aaronsmoore** [ds-modules/ENGIN-7#5]
Lab02 Q6 and Q7 are based on SNAP/BYOB. The text from the question is below:

## Snap

Snap! (formerly BYOB) is a visual, drag-and-drop programming language, as seen in
lecture. Snap! has extended capabilities over Scratch which make it suitable for a
serious introduction to computer science for high school or college students (e.g. it is
used for CS 10 here at Berkeley). Snap! runs in your browser - if you have any trouble,
try a different browser (they recommend Google Chrome).

## Question 6

Complete [this tutorial](http://beautyjoy.github.io/bjc-r/cur/programming/intro/snap/welcome-to-snap2.html?topic=berkeley_bjc%2Fintro_pair%2F1-introduction.topic&course=cs10_fa15.html&noassignment&noreading&novideo) (from CS 10). In this tutorial you will create an account, try
out some test programs, and write your own Kaleidoscope program. (You can ignore
the parts about pair programming. Answering the quiz questions may be helpful - but
answers are not recorded.) You do not need to submit anything for this problem, but
it will be helpful for the next problem.

## Question 7

For the next part, you will create a simulation of a molecule as it travels in a liquid
or a gas - this is known as a random walk, which describes the Brownian motion of a
molecule. (It may help to read this page on random blocks and this page on randomly
moving a character.)

a. Think about how you want to structure your code before you start. Your sprite
should start from the center and then perform a 2D random walk of a particle.
First, change the costume for your sprite from the default arrow shape, by drawing
a square or circle (using the Paint tool under the Costumes tab) of a reasonable
size.

Your sprite should do the following:
1. randomly walk forever starting from the center of the stage (stop the program
with the red button)
2. have a random step size and random direction
3. drag the pen around to show its path, and gradually change the pen color as
it goes
4. play a random note at each step (values between 40 and 90 are good) for 0.1
beats
5. pause between steps by 0.1 seconds (in addition to playing the note for 0.1
beats)
6. make sure it bounces back if it hits the edge of the stage
For this problem, you will submit:

(a) a link to your final Random Walk program (copy the URL). Make sure you have
saved your program to the cloud. Submit your URL by filling out this [Google Form](google.com).

(b) a pdf named `<Firstname>_<Lastname>_Snap.pdf` that contains a screenshot of
your final browser window. You can right click on the Scripts workspace and
click `clean' and it will order your blocks neatly. If you need more room you can
expand the workspace with the sliding bar.

A full Snap reference manual can be found [here](http://snap.berkeley.edu/SnapManual.pdf) but you shouldn't need it unless you
try to get fancy. If you want more details see [this page](http://beautyjoy.github.io/bjc-r/cur/programming/intro/snap/welcome-to-snap2.html?topic=berkeley_bjc%2Fintro_pair%2F1-introduction.topic&course=cs10_fa15.html&noassignment&noreading&novideo).

***

Most of the links are dead and locating the correct ones has been difficult. Do current E7 assignments include these questions? Would they have updated links/instructions?

**Comment by aaronsmoore** [comment]
@mhallal-berkeley do you have access to the current assignments to see if these questions are still used? I can remove them if you feel they are unnecessary.

**Comment by mhallal-berkeley** [comment]
Yes, please remove these questions.

**Comment by aaronsmoore** [comment]
Removed
